sudo      : required
dist      : precise
language  : cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: COMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nasm

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$COMPILER .. && make
